### ISSUE TITLE
Add Current Tab is broken

### ISSUE THREAD

**Issue by mikehopps** [waytab/WayTab#15] opened 2018-06-20 13:50 UTC
If I add a tab using the drop down when when on a page, it works.  Then, if I try to add a different tab, it repeats the first tab I added.  
I added cnn.com using the shortcut.  Then went to fivethirtyeight.com, added it, and got another CNN link on the Waytab page.  I got lots of CNN shortcuts this way.

**Comment by awangg** [comment] 2018-06-20 14:03
@mikehopps I was unable to reproduce the bug. What version are you on? Can you attach some screenshots of what it looks like on the WayTab screen? If the image is the same, then the links will probably the the same unless both images are the default image.

**Comment by mikehopps** [comment] 2018-06-20 14:08
I'm on 1.0.1.   The link definitely goes to CNN, not fivethirtyeight.  Fake
news!


[image: Capture.PNG]
[image: Capture2.PNG]
​

**Comment by mikehopps** [comment] 2018-06-20 14:09
I'm also on Windows right now. Might make it weird.

**Comment by awangg** [comment] 2018-06-20 20:37
@mikehopps I am unable to see the images

![screen shot 2018-06-20 at 4 37 21 pm](https://user-images.githubusercontent.com/26381500/41683317-4226b6e8-74a8-11e8-9960-75351cc694bd.png)

**Comment by mikehopps** [comment] 2018-06-20 21:21
![image](https://user-images.githubusercontent.com/4509544/41685404-61dc7f6c-74ae-11e8-82f8-165293be50d1.png)

**Comment by awangg** [comment] 2018-06-20 22:01
@mikehopps gitcePTioN

**Comment by awangg** [comment] 2018-06-20 23:21
@mikehopps I still haven't been able to reproduce your bug on my mac, but I looked over and tested the code a few times. There might a problem with the chrome.tabs api on Windows but as far as I can tell it isn't happening to me...

I do have an improvement for those annoying non-imaged links though, albeit coming out in 1.0.3.

**Comment by awangg** [comment] 2018-06-20 23:21
@andrewward2001 can you take a look at the functions.js code in the popup?

**Comment by andrewward2001** [comment] 2018-09-08 01:00
This doesn't seem to be an issue (at least not anymore) on Mac or Windows.

**Comment by mikehopps** [comment] 2018-09-08 15:13
Well, I still can't edit the fields.  But, hey, sure, close the issue.
Cool.

**Comment by awangg** [comment] 2018-09-10 20:31
Sorry Hopps, looks like your computer is cursed

**Comment by andrewward2001** [comment] 2018-09-12 01:14
@mikehopps Has this worked itself out yet or is it still an issue? If it is, I would say you should reinstall, but if not I'd like to close this issue.

**Comment by mikehopps** [comment] 2018-09-12 01:15
It fixed itself this morning. Magic! Close it.

**Closed** 2018-09-12 01:50 UTC
Labels: bug, frozen
